apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: myPod
    type: proxy
spec:
  containers:
  - name: nginxcontainer
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  tolerations:
    - key: "team"
      operator: "Equal"
      value: "devops"
      effect: "NoSchedule"   